### ISSUE TITLE
Argument 2 passed to League\Glide\Server::outputImage() 

### ISSUE THREAD

**Issue by karpuzkan** [thephpleague/glide#116]
Hello,
Thanks for glide, it's awesome. I followed ur tutorial and used it before with Laravel 5.1.9 and still working like a charm.

I updated my laravel to 5.2 and trying to set up glide but i have an error if I route for **nested** folder setup.

I checked $server is working. Also single folder route is working too.

**ErrorException in Server.php line 431:
Argument 2 passed to League\Glide\Server::outputImage() must be of the type array, none given, called in laravel/app/Http/routes.php on line 5 and defined**

And my route

    Route::get('img/{path}', function(League\Glide\Server $server, Illuminate\Http\Request $request){
    $server->outputImage($request);
    })->where('path','.+');

Sorry if i missed something...

Thank You

**Comment by reinink** [comment]
Were you using `dev-master`? If so, and you recently updated your Composer dependencies, this would have happened, since we recently launched Glide version 1.0.

Previous Glide only used HttpFoundation, so you could simply pass in a request object like you are doing. However as of version 1.0 the API has changed slightly, and it works with multiple response interfaces. You can read about that [here](http://glide.thephpleague.com/1.0/config/responses/).

The simplest solution to get things working again is to switch back to version `0.3.5`. Good luck!
