### ISSUE TITLE
Chrome Windows

### ISSUE THREAD

**Issue by renege** [thephpleague/glide#123]
Hello,
In Chrome on Windows it often returns a broken image when it renders on the fly. Not in other browsers as far as I know. How to solve/prevent this?

**Comment by reinink** [comment]
Can you give me the error that is being thrown?

**Comment by polargold** [comment]
I am also getting a broken image if i try to use width less than 60 px

�PNG  IHDR%U�Y�	pHYs���+IDATX���KkS[�{�W�6����Mڦ f�@�(�iq�T�O��/��8T��št����Ї �ML��s�>��w 97�>��`��a���z�׊�}_q*�J�j52��i�G�T���T*!X__gkk���b�KKK��	!PJ��E�Ǿ�#����euu��� ��H���e�߿��H)5`�4�Ê�Z-� ��R*��f�����D�u}����4��(�N�B�i�e�8�X,2M�k׮�n�q�V����O�T"�H���$>���0�,�r��R�b��i��J%\�%�R�׃��2SSS'��/�'������,���c޼y����YZZ���277G�Ra}}���C>|����a����J��B��?���ݻw1�L&C����<�_�N�Xduuu �J):�΀w'�^U�~��_�~!�$���Z��\���]��&����d���+7o�Ķm��0߾}�޽{,,,p�߿��h���Gr�J)r��j)%�����@��bbb���-����F�x����o߾%�N���M:�"qI�>�8�o�&���( ضM�^'cY333�B!���Z-\ץ�h �$�ˑJ�x�����?�H�˗/c?~����"� �Nc�6.\@�4��qB��i2;;����i211���~�V�i�/�J)^�x���&�b������:��3;;K��@)E�P�4M.]�D�R�u]����4�'O���dB �0����l6��ϟ?���cnݺ������spp�)%d�Y�>}�R ��)�����3a3�x��z��gϞq�� VVV���DJ����	���˗/�r� {{{t:��8<�V���:�ht�ҿ����O*�²,.^����$�h�0���B)50 zw��������d2�eY�7]שV��J%l� � ���v��Y�B�����^��p]�0����gB� ��w?0����a��v�m�qF��3�F<>)�Z�H$B<�X,2�s�;�����<�an��OMM8ܓ���0�kS�T*5:���x���i���S�V�4�f�9���.����^���q�`����0����{�˭R���cZ�kkk4�M�^�:���y�tA"��3@��E�4`̲7�����Y���I&���(GH�u�����gzz�u�\��e|��L�wo>{����t�] ��ht0�'A�p$��֨V�ܹsgd�����ӛR"��q*� �h)%�f3��t:��O�y�E�>}¶m�� ��v�,..rxx�eYLNN"�`oo�D"���������z�y�x�߿�h4�u�N�C���N�R��m���9��8^JI*�BA��$ �n��D"��a����?����O丽�4���GAJI2��R��L&��ꁏ��y�v��`Y�a�D�����)�g�C�x<���c��/��w!Fɰ���c!�F���B�GS���N��iԓ����o����Z-l�ѳ,��������IEND�B`�

**Comment by reinink** [comment]
Can you share a bunch of your code so I can have a look? Please share your Glide configuration, controller code, and template code if possible. Thanks!

**Comment by joexanderson** [comment]
@reinink Hey, I'm currently experiencing this issue too. Since @polargold didn't get back to you I thought I'd share the code I'm using so you can help me and others out.

My URL is `http://app.dev/resources/xpf/profile/MYKdolYaZkrm4zb57209d276ccd2.jpeg?w=64` and it's returning a broken image. It starts returning broken images when I get down to 171 pixels, anything higher is fine. The image is originally 2000x2000px.

I followed your tutorial here: https://vimeo.com/118089742

Here's my `routes.php`: https://gist.github.com/joexanderson/e2e6a3a10377e70bd049e4b200dc569b
`AppServiceProvider.php`: https://gist.github.com/joexanderson/659390aaada02389de5f25702d41a916

Do you think you can help?
Thanks :)

**Comment by reinink** [comment]
You can get these types of responses when Glide is configured wrong. I'd recommend reviewing the response Glide is returning to make sure no extra content is being sent after the image. Even more important, verify that the headers are correct.

If you are using the `outputImage` approach instead of [responses](http://glide.thephpleague.com/1.0/config/responses/), you very likely need to add an `exit` after. For example:

```php
$server->outputImage($path, $_GET);
exit;
```

Hope that helps!
