### ISSUE TITLE
Is there any way to make Glide use Public folder instead resources?

### ISSUE THREAD

**Issue by denisgruba** [thephpleague/glide#140]
I need to use the folder in Public to store images. Let's say it's 'Public/Uploads' folder.
Is there any way to make glide compatible with the Public routes instead the Resources?

**Comment by reinink** [comment]
Yes, absolutely. Simply configure Glide to point to your public directory instead.

```php
$server = League\Glide\ServerFactory::create([
    'source' => 'path/to/public/uploads/folder',
]);
```

However, be aware that Glide will not work if the image URL actually matches a real file in your public directory, since your web server will actually load that image, instead of hitting PHP with the request. So if you do setup Glide in this way, make sure that your image URL is different. For example, `/img/my-image.jpg` actually points to `/public/uploads/my-image.jpg`.
