### ISSUE TITLE
How to install on a shared server

### ISSUE THREAD

**Issue by AngleV** [thephpleague/glide#148]
Want to use this script but i am on a shared server.
What steps should i do to get it working on a shared server ?

**Comment by reinink** [comment]
You would simply install this like you would any other PHP package. Glide is best installed with Composer, because of it's dependencies, and that's always a bit of a challenge in shared environments. I'd recommend doing some searching for how to best handle installing Composer dependencies in shared environments, this is a pretty well covered topic. For example:

- https://akrabat.com/using-composer-with-shared-hosting/
- http://stackoverflow.com/questions/20894518/how-do-i-install-composer-on-a-shared-hosting

Beyond that, Glide requires no special server software to be installed, other than PHP and the GD extension, which is basically always installed with PHP.

Good luck!
