### ISSUE TITLE
Is Glide images works on all browsers?

### ISSUE THREAD

**Issue by Hacker12345577342** [thephpleague/glide#154]
I am not able to test it but I heard that Glide images is not working on Safari.I want to use Glide and from now I change my all image system to Glide but I want to be sure that is Glide works on all browsers?

**Comment by reinink** [comment]
Yes, it definitely should work on all browsers. Sometimes in situations where Glide is configured wrong you can have issues in some browsers, and not others, depending on how they handle an invalid response. I'd recommend review the response Glide is return to make sure no extra content is being sent after the image in the request. Also check the headers.

If you are using the `outputImage` approach instead of [responses](http://glide.thephpleague.com/1.0/config/responses/), you might need to add an `exit` after. For example:

```php
$server->outputImage($path, $_GET);
exit;
```

Good luck!
