### ISSUE TITLE
Class 'League\Glide\ServerFactory'

### ISSUE THREAD

**Issue by kelvinhalim13** [thephpleague/glide#161]
hello im new a newbie in gilde, i was trying to use glide than i got glide by downloading the zip, when i was trying to use 

    $server = League\Glide\ServerFactory::create([
         'source' => realpath(APPPATH.'../../images'),
         'cache' => realpath(APPPATH.'../../images/cache'),
    ]);

i got error Class 'League\Glide\ServerFactory' not found. Im using codeigniter framework

**Comment by reinink** [comment]
Yeah unfortunately that won't work. This is because the `League\Glide\ServerFactory` hasn't been included (or loaded) in your project, even though it may _exist_ within your project.

Glide is designed to work with [Composer](https://getcomposer.org/), a dependency manager for PHP. Composer ships with an autoloader, which is how most people "include" their PHP class files. You can definitely use Composer with CodeIgniter. If you're new to PHP, I'd highly recommend learning this tool. It's really a must-have for PHP devs.

In fact, if you are new to PHP I'd recommend the [The PHP Practitioner](https://laracasts.com/series/php-for-beginners) on Laracasts. @jeffreyway has graciously made this course available for free. In particular, check out the [Composer Autoloading](https://laracasts.com/series/php-for-beginners/episodes/21) lesson.

Good luck! 👍

**Comment by JeffreyWay** [comment]
😘😘
