### ISSUE TITLE
Why we need to use sign even Cloudinary and other services doesn't do that?

### ISSUE THREAD

**Issue by Alexandra12312312** [thephpleague/glide#172]
I don't want to use signs because there are heavy to use each time we need use sha1 or md5 for each image. I have read documendation of Glide and I have watched your seminar on youtube .Ok it seems like we need to use sign because of heavy image manupulation attack ,but non of cloud services doesn't use that for example here http://res-1.cloudinary.com/demo/image/upload/c_fill,h_32,w_32/bike.jpg .Are these services working differently than how Glide works?or is there another solution without sign?

**Comment by reinink** [comment]
Great question! HTTP signatures are very practical and easy way to prevent server clobbering, which is why Glide uses this technique. Services like Imgix and Cloudinary would undoubtedly also have similar protection methods in place, such as rate limiting. However, since these are full-blown services they have a lot more tooling available to them than just PHP.

If you're really curious you could always ask one of them directly how they do it! 😎
