### ISSUE TITLE
Is Exif a hard dependency for Glide?

### ISSUE THREAD

**Issue by martinbean** [thephpleague/glide#176]
As per the subject: is the Exif extension a hard dependency for Glide? Because I’ve deployed an application and found the version of PHP in that environment wasn’t compiled with Exif, and I don’t have the ability to re-compile or modify it. The exception thrown is:

> Intervention\Image\Exception\NotSupportedException
> Reading Exif data is not supported by this PHP installation.

Looking at my exception backtrace, it seems to be the orientation manipulator triggering the exception.

Is it possible to forego the orientation manipulator, so I can get my application serving images?

**Comment by reinink** [comment]
Yeah, this makes sense since Intevention/Image uses the Exif extension to set the orientation, which Glide does by default on each manipulation. From [their docs](http://image.intervention.io/api/orientate):

> **Note: PHP must be compiled in with --enable-exif to use this method. Windows users must also have the mbstring extension enabled. **

There is no configuration option right now to disable this. However, what you can do is manually configure which manipulators Glide uses, which you can find instructions for [here](http://glide.thephpleague.com/1.0/config/setup/#setup-manually).

Simply omit `new League\Glide\Manipulators\Orientation()` from your list of manipulators and you _should_ be good! 😎

**Comment by martinbean** [comment]
@reinink Thanks for getting back to me. Is it worth adding `ext-exif` to Glide’s *composer.json* file in this case?
