### ISSUE TITLE
 Browser not caching generated images (no 304)

### ISSUE THREAD

**Issue by InfinityWebMe** [thephpleague/glide#185]
Hello,

in reference at this issue : #20  

The issue seems to be in v1 ? I don't found the header if-modified-since.

**Comment by cdowdy** [comment]
@InfinityWebMe  try passing in your request to your response factory as seen [here for laravel](http://glide.thephpleague.com/1.0/config/integrations/laravel/)  

  
laravel example:  

```php  
use League\Glide\ServerFactory;
use League\Glide\Responses\LaravelResponseFactory;

$server = ServerFactory::create([
    'response' => new LaravelResponseFactory(app('request'))
]);  
```   

or for symfony   

```php  
$server = ServerFactory::create([  
  'response' => new SymfonyResponseFactory($app['request']),  
]);  
```  

That "should" do it .... maybe haha.

**Comment by InfinityWebMe** [comment]
@cdowdy  
Hello, I don't use common framework on this project. Why is not by default ? 
Thanks to the reply :)

**Comment by reinink** [comment]
It's not done by default in the `outputImage()` method largely because that isn't really the ideal way of using Glide. We generally recommend working with proper response objects.

Even if you're not using a framework, I'd recommend installing the [HttpFoundation package](http://glide.thephpleague.com/1.0/config/integrations/symfony/). This allows you to optionally pass in a [request object](https://github.com/thephpleague/glide-symfony/blob/master/src/Responses/SymfonyResponseFactory.php#L21), which will be used to figure out the `If-Modified-Since` header.

Completely untested, this would look something like this:

```php
use League\Glide\Responses\SymfonyResponseFactory;
use League\Glide\ServerFactory;
use Symfony\Component\HttpFoundation\Request;

// Setup Glide server
$server = ServerFactory::create([
    'source' => 'path/to/source/folder',
    'cache' => 'path/to/cache/folder',
    'response' => new SymfonyResponseFactory(
        Request::createFromGlobals()
    )
]);

// Output image
$server->getImageResponse('users/1.jpg', ['w' => 300, 'h' => 400])->send();
```

Remember to install the `league/glide-symfony` package:

```bash
composer require league/glide-symfony
```

And for what it's worth, this will be baked into [version 2.0](https://github.com/thephpleague/glide/issues/170), since that will copy with HttpFoundation (and a PSR-7) implementation by default.

Good luck!
