### ISSUE TITLE
Discard default property values in URL

### ISSUE THREAD

**Issue by wbadrh** [thephpleague/glide#188]
Can we safely discard the default properties?

For example:
```
img.php?file=myfile.jpg
img.php?file=myfile.jpg&bri=0
```

Will both create an identical image in the cache folder. 
One file should suffice for both requests.

Unfortunately we cannot simply discard "0".
The exception here:  Gamma with a default value of 1.

Is there a reason for the current behaviour?

**Comment by reinink** [comment]
The reason this happens is because of how Glide generates the hash for an image. It includes all the image parameters, regardless of if they are defaults or not.

Honestly, this could probably be avoided, but the solution would be complex. The issue is that the place where Glide generates this hash is outside of the manipulators themselves, and it really has no idea of what the defaults are at that point.

And truthfully, from my experience, I haven't really run into this as a problem. Sure, the odd extra cached image image might be generated, but that's not really a super big deal.

So I guess at this point, it's not likely to change.
