### ISSUE TITLE
Glide not removing temp files

### ISSUE THREAD

**Issue by ndebarnot** [thephpleague/glide#192]
Hi all,

my /tmp folder gets filled with temporary Glide files such as /tmp/Glide8bQmtG for instance.

How can I find out why they are not removed? (it's not a user rights problem).

Thanks!

**Comment by wbadrh** [comment]
## Deleting cached images

`$server->deleteCache($path);`

Glide does not automatically purge cached images. However, this can be done by your application using the deleteCache() method. Note, grouping cache in folders MUST be enabled in order to delete cached images, which is the default setting.

You can setup a cron job cleaning this folder periodically.

## Disabling the cache

In some situations it may be desirable to disable the cache. For example, you may choose to use a tool like Varnish for caching instead. The best way to do this with Glide is to use an [in-memory adapter](http://flysystem.thephpleague.com/adapter/memory/) for Flysystem. This will prevent any cached images from being saved to your local disk.

`composer require league/flysystem-memory`

```
use League\Flysystem\Filesystem;
use League\Flysystem\Memory\MemoryAdapter;

$server = League\Glide\ServerFactory::create([
    'source' => 'path/to/source/folder',
    'cache' => new Filesystem(new MemoryAdapter()),
]);

$server->outputImage($path, $_GET);
```

http://glide.thephpleague.com/1.0/config/source-and-cache/
http://glide.thephpleague.com/1.0/config/advanced-usage/

**Comment by ndebarnot** [comment]
Hi, thanks for your reply.

The mistake was on my end. Due to wrong file permissions in the cache folder, the resized images could not be moved there and remained in the /tmp folder of the server.

Contrary to what I originally thought it WAS a user rights problem but not in the /tmp folder.

**Comment by reinink** [comment]
@ndebarnot Good to hear you figured it out.

@wbadrh Thanks for stepping in to help out!

**Comment by gopal-g** [comment]
@reinink  May I know what is the idea behind not being able to delete the files with  ```$server->deleteCache($path);``` if group caching being disabled ? How to delete the cached images in such case ?

**Comment by Art4** [comment]
@gopal-g Glide creates a md5 hash from the image path and the arguments, see https://github.com/thephpleague/glide/blob/1.2.2/src/Server.php#L275 `$md5 = md5($sourcePath.'?'.http_build_query($params));` and stores the manipulated image under this name. There is no way to determine if some hashes are the result of manipulating the same source image. So you can't know which images you could delete and which not. Expect if you prefix an identifier to the cached filename or store them in separate folders per source. And thats exactly the feature that group caching does.

**Comment by gopal-g** [comment]
Nice, thanks for the explanation. I will simply enable group caching and delete that image which sounds just fine :) Thank you for this extra-ordinary package (y) @Art4

**Comment by barryvdh** [comment]
My /tmp folder is also filling up, leading to errors when it reaches 100%. It doesn't have any problems showing the images, so not sure if it's an permissions issue.

Any other ideas? Did anyone encounter this?

**Comment by barryvdh** [comment]
Submitted a PR in https://github.com/thephpleague/glide/pull/238 to delete files even when an Exception occurs
