### ISSUE TITLE
[Question] Sign URL on client side

### ISSUE THREAD

**Issue by benkelukas** [thephpleague/glide#258]
Hi,
this is more of an architectural question than issue, but it would be awesome if you had anything to share regarding this.
So, i have an API endpoint that is using glide to generate images.
I have a client application, that is using this API to fetch those images
Now, i would like to use signed requests, but the issue is, i need to use signing key for this. On the server it is fine, but if i share a signing key on the client, so that client can generate the signed url, then i am exposing the signing key and making it easy for hackers to use the key and flood the server anyway.
Do you see any solution to this? Or should I just use rate limiting on the endpoint and hope for the best?

Thanks in advance for Your time.

**Comment by baileylo** [comment]
@benkelukas,

Here's my two cents, though I'm eager to see what other says. You can try to _hide_ the signing key some where in the client(I'm assuming it's a compiled native app). You still run the risk of somebody decompiling the binary and finding the key.

You could also try using something like [PKCE](https://www.oauth.com/oauth2-servers/pkce/). Once you've authenticated the app, you could transmit a short lived token. I forsee a couple of issues here. The token can be intercepted by watching network traffic and then re-used to generate images. The images that were generated with the token would have an inherently short TTL, as the signing token would expire. This could be mitigated with a longer CDN cache. But you'll always have the issue of images that were valid now returning an error.

What has worked for me is producing the images from an API. You would only want to do this when the API _knows_ the image. Otherwise you're exposing the resizer indirectly. For this scenario, imagine you have a `/users/{id}` endpoint on your api that returns a `profileUrl`, you'd replace this `profileUrl` with a dictionary containing `large`, `small`, and `medium` and each one having a pre-signed URL. The API here is the source of truth for the image. This scenario has a two benefits. It eliminates your initial security concern about leaking the signing token. Secondly, It provides you with more flexibility. Assume glide for some reason changes their API, this could be adding a new parameter you want to use. It's far easier to update the URL generated by your API, then to convince users to update their apps to get the newest URL options.

**Comment by benkelukas** [comment]
@baileylo 

Thanks a lot for Your elaborated response. 

The client is actually a frontend web app built with Nuxt.js (Vue.js and SSR) but I think the principle is the same.

I will go with predefining images on the API side, it seems like the best solution, although one looses the flexibility of client application being able to generate images in whatever format it needs, but that is better than exposing the API server for attacks.

I'm closing this, since i got my answer, but if anyone has additional suggestions, feel free to comment.
