### ISSUE TITLE
very slow page load 

### ISSUE THREAD

**Issue by tkart38** [thephpleague/glide#287]
hi i've notice that the image loading is very very slow.
any advice?

![Immagine 2020-10-06 171934](https://user-images.githubusercontent.com/16717223/95222078-6c963800-07f8-11eb-996c-435d36a7d402.png)

**Comment by pjdevries** [comment]
I'm experiencing the same and second this request for advice.

**Comment by tgalopin** [comment]
Hi!

This is probably due to the resource-intensity of image processing, and unfortunately, this is something difficult to fix.

There are ways you can decrease this intensity:

* Decrease the image of the source file: on upload, resize the source file for instance to maximum 2500x2500. This will avoid having too big image being manipulated by Glide at runtime ;
* Put as many images as you can in cache. Don't hesitate to put very long cache mechanisms in place, as the parameters of the URL define what the image should look like so it works very well with HTTP cache (Varnish for instance)
* Finally, try to find which operation is the slowest. By using a tool like [Blackfire](https://blackfire.io) you can try to find which operation on the image is the slowest: the resize, an overlay, a color manipulation, etc. If this operation can be optimized (perhaps by precalculating things, or creating an image you can simply embed instead of build at runtime), you can perhaps decrease the time necessary to render the image

Generally speaking however, Glide was design as a runtime library. That makes it very flexible because the source images are used at runtime, but it also makes it a slower than simply rendering images that were already built. That's kinda normal :) . Depending on your situation, it may make sense to prepopulate Glide cache at upload for some settings.

**Comment by pjdevries** [comment]
Thanks for your swift reply @tgalopin

I will take your suggestions at heart and see if I can improve things.

**Comment by ADmad** [comment]
Closing as there's nothing to be done in Glide's code for this issue.
