### ISSUE TITLE
Only check parameters used by Glide for signature/cache

### ISSUE THREAD

**Issue by barryvdh** [thephpleague/glide#29]
Right now, all query parameters are checked when generating the cache or validation/creating the signature. Perhaps we could whitelist the parameters used for Glide? This would allow arbitrary query parameters to be skipped. This could happen in 3rd party libs etc, which add a timestamp to clear browser caches for example, or custom parameters (tracking?).
Right now, each (unused) parameter will create a new cache object.

I could create a PR if you want.

**Comment by reinink** [comment]
I had considered this, and early versions of Glide actually did this. But then I did some refactoring, and this became really difficult to do, and I questioned if Glide should even worry about this. Worse case someone passes extra unnecessary parameters, and it generates a new file, who cares? Yes, I get that this requires additional resources, and storage space, but the simple solution here is to just not pass unnecessary parameters.

If you familiarize yourself with how the Manipulators work, you'll notice it's easy to add additional manipulators. This is super handy, as developers can basically change Glide however they want for their particular project. If you need some manipulator that doesn't exist, just add it. It's not hard at all. However, this means there isn't a set number of functions available that we can cross reference when generating the cache filename.

To do this properly each manipulator would have to update an array at the `Glide\Server` level, something `$server->usedFunctions`. However, the manipulators currently do not have access to server object. They simply accept an instance of `Intervention\Image\Image`, modify it, and return an instance of `Intervention\Image\Image`.

So, all this to say, I'm not convinced the effort to track this is worth the extra complication in the code base. Your use case examples are fair, but you could just do this:

```php
// Your request object
$request = Symfony\Component\HttpFoundation\Request::createFromGlobals();

// Strip unnecessary query parameters
$params = $request->query->all();
unset($params['revisions'], $params['tracking_code']);

// Output image
$glide->outputImage(
    $request->getPathInfo(),
    $params
);
```

**Comment by barryvdh** [comment]
Okay I indeed ended up just removing some parameters from the query array. When the parameters are flexible, I understand it isn't as easy as I initially thought ;) Thanks anyways!

**Comment by reinink** [comment]
Okay cool. I'm not saying I'll never look at this in the future, I just want to be careful how much stuff I make Glide do, especially when there are so many unique project specific use cases. And many of the project specific customizations can be done prior to Glide by simply editing the `$path` and `$params` method parameters.

I've actually already added `base_url`, which modifies the `$path`, which is handy because this is a very common problem, but even there I was concerned that I was making Glide do too much. It's really not that hard to strip the base path out of the `$path` before sending it over to Glide. I'm trying to find a good balance here.

Thanks for your interest in this project @barryvdh and thanks for contributing!
