### ISSUE TITLE
Response times increase when making glide requests in a loop

### ISSUE THREAD

**Issue by johncarter-** [thephpleague/glide#290]
I am building a Laravel 8 app. I have some images related to products.

When I loop the images the response times from my local environment grow with each request. See the screenshot:

![image](https://user-images.githubusercontent.com/3776888/96896715-c13ae380-1485-11eb-8752-0061146dc011.png)

I am using the `exact` code from the controller shown in the docs:   
https://glide.thephpleague.com/1.0/config/integrations/laravel/#installation

My route is:   
`Route::get('glide/{path}', [App\Http\Controllers\GlideImageController::class, 'show'])->where('path', '.*');`

And my view looks like this:

```
<x-test-layout>

    @foreach ($products as $product)
    {{-- <img class="max-w-sm" src="/storage/{{ $product->imageUrl() }}" alt=""> --}}
    <img class="max-w-sm" src="/glide/{{ $product->imageUrl() }}" alt="">
    @endforeach

</x-test-layout>
```
The non-
N.B. `x-test-layout` is just a bare bones html boiler plate.

Can anyone tell me what am I doing wrong?

**Comment by johncarter-** [comment]
In addition. I have recreated this on a fresh install.

**Steps to reproduce in Laravel context:**

1. Setup new project
```
composer create-project --prefer-dist laravel/laravel glidetest
&& cd glidetest
&& composer require league/glide-laravel
```

2. Add the glide route in `routes/web.php`:

```
Route::get('/', function () {
    return view('welcome');
});

Route::get('/img/{path}', [App\Http\Controllers\ImageController::class, 'show'])->where('path', '.*');
```

3. Create the ImageController the same as in the docs
```php
<?php

namespace App\Http\Controllers;

use Illuminate\Contracts\Filesystem\Filesystem;
use League\Glide\Responses\LaravelResponseFactory;
use League\Glide\ServerFactory;

class ImageController extends Controller
{
    public function show(Filesystem $filesystem, $path)
    {
        $server = ServerFactory::create([
            'response' => new LaravelResponseFactory(app('request')),
            'source' => $filesystem->getDriver(),
            'cache' => $filesystem->getDriver(),
            'cache_path_prefix' => '.cache',
            'base_url' => 'storage',
        ]);

        return $server->getImageResponse($path, request()->all());
    }
}
```

4. Add a test image to `storage/app/public/test.png`. In my case its a png of 2400px x 1400px ~90kb.

5. This in `resources\views\welcome.blade.php`
```
@for ($i = 0; $i < 50; $i++)
<img class="max-w-md w-full" src="img/public/test.png?w=50{{ $i }}&fm=webp" alt="">
@endfor
```

6. Check the browser network tab.

7. Loss!

**Comment by shyim** [comment]
Maybe session locking?

**Comment by johncarter-** [comment]
Can you elaborate a bit?

**Comment by johncarter-** [comment]
I feel this must be related to #15 .

The issue is known, but there are no workarounds,is that right?

**Comment by shyim** [comment]
Maybe call in your Controller first 
```
session_write_close();
```

and look into the requests if its getting better

**Comment by johncarter-** [comment]
Hey @shyim thanks so much for the tip, but that doesn't fix it unfortunately.

**Comment by tgalopin** [comment]
Hello @johncarter-!

Do you know which PHP server you're using locally? I think the native PHP development server doesn't handle requests in parallel, which would mean images would have to be loaded one after another.

**Comment by johncarter-** [comment]
Locally I am using:
- Laragon on Windows 10
- PHP 7.4.6
- Nginx 1.14.0

But I have also tested it on a Forge provisioned DO droplet which exhibits the same compounding response time.

**Comment by johncarter-** [comment]
You can see it in action here:

https://demo.jcwd.dev/ 

https://github.com/johncarter-/demo

**Comment by tgalopin** [comment]
After having a look at your waterfall, it actually makes a lot of sense: Google Chrome (and many browsers) limit the amount of parallel requests made to a same domain by the browser. Google Chrome limits this amount to 5, meaning no more than 5 requests are going to be executed at the same time.

First, Chrome launches your 5 first requests for images. Because Glide takes a bit of time to render the image, the images are not rendered all the the same time, some are slower than others. As soon as an image finished loading, Chrome starts the next request to your server (cap-navy.jpg), then the next one, etc.

This behavior is expected and works this way in all web pages. The main difference in your situation is that you use Glide instead of preexisting images served by nginx or apache. Glide takes a long time to render the generated image, thus this feeling of slowness.

To fix this issue, there are several ways:

1. you can use backend cache (the "cache" option of Glide) if you don't already: that's going to cache the generated image in your storage, thus rendering it much faster afterwards ;
2. you can use HTTP cache to serve cached images directly from a CDN, CLoudflare or a similar service (but only in production)

Otherwise, that's a known drawback of Glide: generating imags at runtime is extremely useful to create image variants only when you need them and thus develop much faster, but it also means that you have to generate the image during a request.

An optimization you could have a look at would be to resize the source images when you receive them, so that the source image is always at most a 2500x2500 for instance. This would help Glide render images faster as the source image would be smaller.

**Comment by reinink** [comment]
Well explained @tgalopin!

What you can also do in these situations is pre-generate the cached versions for known image sizes. To do this, simply have a background job generate the the known image sizes. This job can either call the image endpoint (causing the cache version to be generated), or do this manually via Glide:

```php
// Generates the image
$server->makeImage($path, array $params);
```

Hope that helps!

**Comment by reinink** [comment]
> An optimization you could have a look at would be to resize the source images when you receive them, so that the source image is always at most a 2500x2500 for instance

Also, FWIW, I'd probably discourage this...simply because you never know when you want larger sizes. I always like to keep the originals as they are, and then pre-cache as needed.

**Comment by johncarter-** [comment]
Thanks for both your help guys.

I had actually tested to see if I was receiving cached images or generating them at runtime by adding `info(cacheFileExists($path) ? 'cached' : 'generated' );` to the `show` method to log the status of the image.

```php
<?php

namespace App\Http\Controllers;

use Illuminate\Contracts\Filesystem\Filesystem;
use League\Glide\Responses\LaravelResponseFactory;
use League\Glide\ServerFactory;

class ImageController extends Controller
{
    public function show(Filesystem $filesystem, $path)
    {
        // N.B. Log the cache status of this path
        info(cacheFileExists($path) ? 'cached' : 'generated' );

        $server = ServerFactory::create([
            'response' => new LaravelResponseFactory(app('request')),
            'source' => $filesystem->getDriver(),
            'cache' => $filesystem->getDriver(),
            'cache_path_prefix' => '.cache',
            'base_url' => 'storage',
        ]);

        return $server->getImageResponse($path, request()->all());
    }
}
```

It showed that on the second load they were all loading from the cache (as expected) but the requests were still really slow.

I will confirm / recreate this again just to make sure I'm not talking codswallop.

**Comment by johncarter-** [comment]
Okay, so serving the cached files is rapid on that demo project is rapid.

It must be something project specific that is happening. I will investigate and report back.
