### ISSUE TITLE
Codeigniter Responses

### ISSUE THREAD

**Issue by web1989** [thephpleague/glide#299]
Hello
Response to Codeigniter doesn't have it on the list, would anyone have a solution?
https://glide.thephpleague.com/1.0/config/responses/

thanks :)

**Comment by Lustmored** [comment]
To be honest writing `ResponseFactory` for glide is extremely easy. You might as well create one in your project - just implement `ResponseFactoryInterface`.

For inspiration take a look at PSR-7 one that is bundled with Glide and don't hesitate to ask for help. I don't know CodeIgniter so cannot help you more but show direction :)

**Comment by tgalopin** [comment]
As @Lustmored said, it should be quite straightforward to create a ResponseFactory. I'm not in favor of adding too many response formats in the core library, because creating its own is mostly about copy-pasting and adapting https://github.com/thephpleague/glide/blob/master/src/Responses/PsrResponseFactory.php.

If you wish to provide a factory as an open-source package, I'd be happy to link it in the doc though.
