### ISSUE TITLE
Is it possible to disable cache?

### ISSUE THREAD

**Issue by sagikazarmark** [thephpleague/glide#30]
I want to give varnish a try, and I don't want files stored twice in my filesystem. Is it possible to disable cache?

**Comment by reinink** [comment]
Not at the moment, no. I had no idea anyone would ever want to that, but that makes sense if you're using Varnish. Can you leave this with me to add a new method for this? For the time being maybe just save the cached file to `sys_get_temp_dir()`?

**Comment by sagikazarmark** [comment]
I probably found the solution. IIRC there is a null adapter in flysystem. That might work.

**Comment by reinink** [comment]
Haha, yep, that would probably work too. ;)

**Comment by xtrasmal** [comment]
Is this repo free for pull requests? I'd like to add something like this:

Current situation:
```php

    /**
     * Get the source file system.
     * @return FilesystemInterface The source file system.
     */
    public function getSource()
    {
        $source = null;

        if (isset($this->config['source'])) {
            $source = $this->config['source'];
        }

        if (is_string($source)) {
            return new Filesystem(new Local($source));
        }

        if ($source instanceof FilesystemInterface) {
            return $source;
        }

        throw new InvalidArgumentException('Invalid `source` parameter.');
    }

```

Preferred situation:
```php
    /**
     * Get the source file system.
     * @return FilesystemInterface The source file system.
     */
    public function getSource()
    {
        $source = null;

        if (isset($this->config['source'])) {
            $source = $this->config['source'];
        }

        if (is_string($source)) {
            return new Filesystem($this->adapter($source, $adapterclass));
        }

        if ($source instanceof FilesystemInterface) {
            return $source;
        }

        throw new InvalidArgumentException('Invalid `source` parameter.');
    }
// Add the source and the adapter, f.e. 'League\Flysystem\Adapter\Null'
    public function adapter($source, $class)
    {
        return new $class($source);
    }
```

**Comment by reinink** [comment]
Hi @xtrasmal, can you explain to me exactly what you're trying to do? I'm sort of confused. If you're simply trying to pass the Null adapter to the Glide factory you can just do this:

```php
$server = League\Glide\ServerFactory::create([
    'source' => 'path/to/source/folder',
    'cache' => new League\Flysystem\Adapter\Null(),
]);

```

**Comment by kevin-thackorie** [comment]
Hi @reinink, passing an instance of Flysystem's NullAdapter (there is no Null) as you suggested does not work:

```
InvalidArgumentException in ServerFactory.php line 90:
Invalid `cache` parameter.
```

I believe it has to do with the following check on line 86 of ServerFactory.php just before the InvalidArgumentException gets thrown:

```
if ($cache instanceof FilesystemInterface) {
    return $cache;
}
```

Because: NullAdapter extends AbstractAdapter which implements AdapterInterface which extends ReadInterface. So it is not an instance of FilesystemInterface.

I believe this is a bug as there is currently no way to turn off caching, which I would like to so as to let a CDN handle caching managed by headers.

Thoughts?

**Comment by reinink** [comment]
Yeah, agreed, I'll add the option to disable the cache in an upcoming release.

**Comment by shyam-achuthan** [comment]
Is there a way to delete the cached files for a particular image?
Say i have a profile image getting uploaded to the S3 which is scaled at different ui, when the user changes the image it wont change the image endpoints but glide actually serves the old cached images based on old requests.

**Comment by kevin-thackorie** [comment]
@shyam-achuthan What you're describing is cache invalidation; something that is discussed in [another issue](https://github.com/thephpleague/glide/issues/7).

From my understanding, there is currently no cache invalidation handling in Glide. I submitted a [pull request](https://github.com/thephpleague/glide/pull/46) to allow disabling of the cache so that caching - and invalidation - could simply be handled by another layer like a CDN (e.g. Amazon CloudFront) or a reverse proxy (e.g. Nginx).

**Comment by xtrasmal** [comment]
cache invalidation :+1:

**Comment by xtrasmal** [comment]
That is my problem

- 

> Op 20 mrt. 2015 om 14:17 heeft "Shyam Achuthan" <notifications@github.com> het volgende geschreven:
> 
> Is there a way to delete the cached files for a particular image?
> Say i have a profile image getting uploaded to the S3 which is scaled at different ui, when the user changes the image it wont change the image endpoints but glide actually serves the old cached images based on old requests.
> 
> —
> Reply to this email directly or view it on GitHub.
> 



Met vriendelijke groet, With kind regards,

Xander Smalbil

Netbulae Virtualization Experts 

----------------

	Tel: 053 20 30 270 	info@netbulae.eu 	Staalsteden 4-3A 	KvK 08198180
 	Fax: 053 20 30 271 	www.netbulae.eu 	7547 TA Enschede 	BTW NL821234584B01

----------------

**Comment by reinink** [comment]
Hey all, I've finally got a good solution to this cache disabling problem. See #56.
