### ISSUE TITLE
Images served as text/html

### ISSUE THREAD

**Issue by jasonvarga** [thephpleague/glide#35]
Been using Glide locally in our Laravel app and everything works really well.

We just pushed the app to production using Forge, and everything that Glide generates is served as `text/html`. Static images outside of Glide are served with their appropriate mime type.

When using a Glide URL inside an `<img />` tag, they display correctly, although still as `text/html`. If we view the URL in the browser directly, we just see the garbled mess you'd expect when viewing an image as text.

This is likely some sort of server configuration issue, but asking here anyway because it appears to be Glide-specific.

Any help would be appreciated.

**Comment by reinink** [comment]
Thanks for posting this Jason. Just so you know, this is how Glide currently sets the `Content-Type`:

``` php
$response->headers->set('Content-Type', $this->cache->getMimetype($this->path));
```
Full context [here](https://github.com/thephpleague/glide/blob/master/src/Http/ResponseFactory.php#L63).

So it would seem that the Flysystem `getMimetype()` method isn't returning the correct value. And how that is resolved will be different for each Flysystem adapter you use.

Where are you storing your cache in production? S3? Locally? Other?

**Comment by jasonvarga** [comment]
I'm using S3, but changing it to local doesn't seem to have an effect.

**Comment by jasonvarga** [comment]
Tinkering around in the code, in this file:

https://github.com/thephpleague/glide/blob/master/src/Server.php#L254-L256

If I `return` the `ResponseFactory` instead of `$request`, it works. I don't know what sort of repercussions this would have...

**Comment by reinink** [comment]
Hmm, now I'm totally confused. Basically that line generates the response, and sends it right away. This allows you to do this:

``` php
$glide->outputImage($request);
```

However, if you actually wanted the image response object, you could do this:

``` php
$response = $glide->getImageResponse($request);
$response->send();
```

If you were to change the Glide code to return `ResponseFactory::create($this->cache, $request, $this->getCachePath($request))->send();`, it would essentially do the same thing it does now (output the response), however the `send()` method returns and instance of the response object, so that is what you'll get back instead of an instance of the request object. You can see that [here](https://github.com/symfony/HttpFoundation/blob/master/Response.php#L384).

**Comment by jasonvarga** [comment]
Huh. If I change my controller code from

```
$server->outputImage($request);
```
to
```
return $server->getImageResponse($request);
```

It works.

**Comment by reinink** [comment]
That does make sense, since Laravel knows how to process a HttpFoundation Response object. Laravel actually uses HttpFoundation for it's request and response objects. Still, it doesn't entirely explain why just doing `$glide->outputImage($request);` doesn't work.

I'd be curious if this would work:

``` php
$glide->outputImage($request);
exit;
```

**Comment by jasonvarga** [comment]
Yes, that works too. I'm using Laravel 5, if that helps at all.

**Comment by reinink** [comment]
I think what is happening is that you're outputting the image using Glide. However, since you are not returning anything from your controller, Laravel considers it a blank, plain-text page, and is probably adding headers for that. Now that still doesn't make total sense for me, because you cannot set headers after already outputting content, unless Laravel is using output buffering, which is very well could be.

Still totally puzzled why it works locally though.

**Comment by jasonvarga** [comment]
You and me both. Returning the image response fixed my problem, so you can consider this issue closed from my perspective.

Feel free to keep it open if you need to dig deeper. Let me know if I can be of any more help.

**Comment by reinink** [comment]
Yeah, I'll close it for now, but will probably dig deeper still. Thanks for making me aware of this!

**Comment by hanishassim** [comment]
Hi, it seems that I experience this same issue, but I'm storing my cache in Google storage bucket. When I try to store locally, it works fine. When trying to store in google storage, it got stored as an object, as shown below:
![screen shot 2017-01-06 at 2 46 44 am](https://cloud.githubusercontent.com/assets/4571502/21693045/646e1a7e-d3ba-11e6-9d9f-b5bbcc2e77a4.png)

**Comment by nicolas-t** [comment]
Yup, for me too cache is stored as application/octet-stream

maybe because it has no extension ?

**Comment by ametad** [comment]
> Hi, it seems that I experience this same issue, but I'm storing my cache in Google storage bucket. When I try to store locally, it works fine. When trying to store in google storage, it got stored as an object, as shown below: ![screen shot 2017-01-06 at 2 46 44 am](https://cloud.githubusercontent.com/assets/4571502/21693045/646e1a7e-d3ba-11e6-9d9f-b5bbcc2e77a4.png)

Thank you! I've searched for the whole wrong kind of reasons why I got the `application/octet-stream` header instead of the `image/*` header... And fortunately I saw your comment all of a sudden.. Finally I can fix my problem, so thank you.
