### ISSUE TITLE
Focal point support

### ISSUE THREAD

**Issue by ducktype** [thephpleague/glide#36]
Actually does not seems possible to specify a custom centering point for resize fit/crop operations.

Some cms allow the user to specify the focus coordinates for each image.

I propose to add an argument like this focal_coords=20%:70% to say that the focal point will be at 20% x and 70% y.

**Comment by reinink** [comment]
Hello, I'm not sure I'm following you entirely. Are you suggesting that the [crop mode](http://glide.thephpleague.com/api/size/#crop-mode-crop) option isn't sufficient? It currently accepts `top-left`, `top`, `top-right`, `left`, `center`, `right`, `bottom-left`, `bottom` or `bottom-right`.

**Comment by ducktype** [comment]
Yes i think "kayaks.jpg?w=300&h=300&fit=crop&crop=left" should also allow crop=20%:70% to specify exacly the position that needs focus, but seems not supported by intervention/image
i've opened: https://github.com/Intervention/image/issues/327

**Comment by jackmcdade** [comment]
I'd love to see this as well.

**Comment by reinink** [comment]
As you can see in issue #75, I've proposing a focal point syntax of `crop-50-50`. These would be percentages, where the first value would represent the `x` position and the second the `y` position. The benefit of using percentages is that they would work for images of different sizes (with the same ratio of course).

**Comment by reinink** [comment]
However, I do still have questions though. The point of the focus points (center, top-left, top-right, etc.) is to help with the cropping, but the actual dimensions are still based on the `w` and the `h` values. That means if you were to choose `crop-1-1` you would essentially get the same results at `crop-top-left`. Does that make sense?

If you want really fine control over the cropping with specific dimensions, then you would just use the current `rect` option.

**Comment by jackmcdade** [comment]
Makes perfect sense. I dig it.

**Comment by ducktype** [comment]
I don't think the rect option is the same as specifying the point of interest in percent coordinates, simply because with the first one you are delegating the rect calculations to the client but the client need the image dimensions to do that. I mean that the focus point percent position option is simply an unobtrusive way to specify the rect option. Does make sense to you?

**Comment by reinink** [comment]
@ducktype Not sure I'm following entirely. Sounds to me like your making the case for this feature, because it's simpler than a `rect` cropping. I don't disagree, however I was more trying to get a clear understanding of how this feature would work. Please confirm the following:

When you use the `rect` feature, you manually set the  `width`, `height`, `x` and `y` coordinates. This crop occurs before any resizing, which means you must know the source image's dimensions to do this. This feature is awesome when used in conjunction with a crop interface, like [jCrop](http://deepliquid.com/content/Jcrop.html).

However, the `fit=crop` option works different, in that the crop happens at the time of resize. This is handy, because you don't need to know the source image's size. Just set your `w` and `h` options, and it works. However, that leaves the `x` and `y` coordinates undefined, which is where the position option becomes helpful (top-left, top-right, etc).

This proposed focal point option will allow for more exact setting of the `x` and `y` coordinates. Using percentages based on the source image makes it easier, since you don't need to know the source image's dimensions.

Does that sound about right?

**Comment by reinink** [comment]
I think the other thing to remember with the `fit=crop` option is that it's not meant to do specific cropping, like the current `rect` feature. Rather, it's part of the resize option, and when you choose `fit=crop` it says "crop off any access image that falls outside of these dimensions after the resize is complete".

The crop position is more like a "gravity" setting (as it's called with ImageMagick), where the resize will fill up as much of the image as possible, and then the gravity setting will specify what part of the image it will keep, and what part it will cut off.

**Comment by reinink** [comment]
So, to make this clearer, if you were to have a source image with the dimensions of `1000x500`, and were to do a resize to `500x500` with a `fit=crop-50-50`, the crop position would only affect the horizontal cropping, not the vertical cropping, since the source image is already has a height of 500px.

**Comment by ducktype** [comment]
Yes it's exacly how i think it should work. 

Probably i've misunderstood something in your previous answers, sorry. 

About the percentage coordinates i think will be clearer to specify it in the value and not the name of the argument.

Something like "gravity=20-70"?

Naming it related to crop is good? If it have a more generic name this open the possibility to use it with different image actions in the future. 

Will make sense to also support 0-1 ranges in decimals when more precision is needed? Like "gravity=0.5428-0.6952"? 

An autodetect on the gravity value will be required to switch between the two cases but i think it's better than adding another argument.

**Comment by jasonvarga** [comment]
Just referencing my explanation of the feature from the Intervention/Image repo.

https://github.com/Intervention/image/issues/327#issuecomment-114138754

**Comment by reinink** [comment]
@jasonvarga Good call. Just so you know, I'm not going to have this added for the 1.0 release. I really want to get 1.0 out soon, and I don't want this to hold it up. Ideally this functionality would be added to Intervention first. However, there hasn't been much response from that end yet, and apart from actually writing the PR, I doubt it will happen very soon. We can always add it as a 1.1 feature.

**Comment by jasonvarga** [comment]
Oh, no rush at all, I was just dropping it in.

Get 1.0 out, its great! :shipit:

**Comment by reinink** [comment]
As of this morning (8a27971140645bf07507c82b9bd53333ddf2c374), focal point cropping is now supported in Glide!

Simply pass in two percentage values to the `crop` fit option, like so:

```php
<img src="kayaks.jpg?w=500&h=500&fit=crop-33-66">
```

There is actually talk about this getting added to Intervention directly, however I didn't want to have to rely on a bleeding-edge version of that library, as it makes dependency resolution much more strict.

**Comment by jasonvarga** [comment]
Awesome!

**Comment by reinink** [comment]
@jasonvarga Thanks! Hoping to have 1.0 tagged VERY soon, now that I've had some time to spend on Glide again. My goal is before 2016.

**Comment by reinink** [comment]
Added to docs: http://glide.thephpleague.com/1.0/api/crop/#crop-focal-point
