### ISSUE TITLE
Problem with creating a signature

### ISSUE THREAD

**Issue by keithslater** [thephpleague/glide#41]
I just started using Glide and I am attempting to set up signatures for the images. I believe I'm about 99% there but I'm having a problem with it.

I am doing this - 

    $urlBuilder = UrlBuilderFactory::create($url, 'key');

    $url = $urlBuilder->getUrl('image.php', ['image' => $path, 'w' => $width, 'h' => $height]);

When doing this, the result of $parts['path'] inside the getUrl method is /image.php.

However when doing this -

    SignatureFactory::create('key')->validateRequest($request);

The output of $request->getPathInfo() in validateRequest() method is just a /.

Because of this, the signatures don't match. Any idea how I can fix this?

**Comment by renege** [comment]
Same here. Maybe someone can make a good example? Will be usable for everyone, looks like from the docs it's a create feature.

**Comment by reinink** [comment]
@keithslater Hmm, I'll have to take a closer look at this to understand what's going wrong. Are you able to provide me example URLs that you're working with?

**Comment by keithslater** [comment]
Sure, I'm doing something like this - http://www.domain.com/image.php?image=company_logos/original/1.png&w=250&h=100

Then when I call it, I'm doing this - 

    $url = $urlBuilder->getUrl('image.php', ['image' => $path, 'w' => $width, 'h' => $height]);

Path would be - company_logos/original/1.png

**Comment by reinink** [comment]
Okay, so I think i see what's going wrong here. Glide is designed for URLs that work like this:

```
http://www.domain.com/img/company_logos/original/1.png&w=250&h=100
```

And then you would create route to accept those image requests, something like this:

```php
get('/img/{path}', function ($path) {
    $glide->outputImage($path, $_GET);
});
```

The reason that URL isn't working for you is because `image.php?image=company_logos/original/1.png&w=250&h=100` should resolve to to `/image.php` when `getPathInfo()` is called.

To make a path like `/img/company_logos/original/1.png` work, you would have to setup URL rewriting, which is pretty standard on modern PHP projects.

Having said that, it would probably be helpful to offer something like this as well with Glide, instead of having to use the HttpFoundation request object:

```php
SignatureFactory::create('key')->validateRequest($path, $_GET);
```

I'll add that to my to-do list.

**Comment by reinink** [comment]
As promised: 615861ad6c00151f8ddd36ddfccbf36ceede8554

I'll get this tagged as soon as possible.

**Comment by renege** [comment]
promising! can you please update docs also with a good example to use this signature-feature?

**Comment by keithslater** [comment]
Awesome, thanks.
