### ISSUE TITLE
Add an Flysystem HttpAdapter for external URL consumption

### ISSUE THREAD

**Issue by renege** [thephpleague/glide#42]
How can I use Glide for referring to external images?

**Comment by reinink** [comment]
Hello @renege, there currently isn't a way to do this since there is no HTTP adapter Flysystem. Which makes sense if you think about it, since HTTP isn't really a file system...it's read-only. However, I do understand why this would be helpful for Glide.

The great thing about Flysystem is that you can write your own adapters for it. I already have a roughly working `HttpAdapter` prototype that I've started on my machine, although I think it needs some updating to work with Flysystem version 1.0.

This is something I hope to add to Glide as soon as I find the time!

**Comment by harikt** [comment]
oh :+1:  .

**Comment by kevin-thackorie** [comment]
+1 for this enhancement :) An HTTP adapter would be tremendously useful.

**Comment by reinink** [comment]
Update: I've been speaking with @frankdejonge, and it looks like we're going to be adding an official Flysystem supported adapter for this very soon.

**Comment by reinink** [comment]
Just realizing now that I already had an issue opened for this. Se #16. Going to close this one, as it's a duplicate.
