### ISSUE TITLE
Image not found when it already exists

### ISSUE THREAD

**Issue by Lloople** [thephpleague/glide#44]
I'm getting the error `League \ Glide \ Http \ NotFoundException 
Could not find the image`. But I checked it already exists. For example:

The error says this: `Could not find the image 'C:\Users\David\www\canae\public/uploads/pages/red.jpg'.`

But if I paste that link into the browser, I get the image:

![cake](https://cloud.githubusercontent.com/assets/5665466/6546910/5bd825b6-c5c6-11e4-993d-3adc26239c56.PNG)

Here's the configuration of Glide in Laravel 5 Service provider:
```
    $this->app->singleton('League\Glide\Server', function ($app) {
        $filesystem = $app->make('Illuminate\Contracts\Filesystem\Filesystem');

            return \League\Glide\ServerFactory::create([
                'source' => $filesystem->getDriver(),
                'cache' => $filesystem->getDriver(),
                'source_path_prefix' => public_path().'/uploads',
                'cache_path_prefix' => public_path().'/uploads/.cache'
            ]);
        });
```

Any idea what I'm doing wrong?

**Comment by reinink** [comment]
I wonder if this has something to do with windows. Are you able to just try Flysystem on it's own to see if the file exists? For example, something like this:

```php
use League\Flysystem\Filesystem;
use League\Flysystem\Adapter\Local as Adapter;

$filesystem = new Filesystem(new Adapter('/path/to/your/files'));

var_dump($filesystem->has('your_file.jpg'));
```

If that works, then it's a problem with Glide not creating paths properly. Unfortunately I don't have a windows system handy to test this on, so your help would be much appreciated!

**Comment by Lloople** [comment]
Thanks for your reply Jonathan,

Of course I will do what you say as soon as I get home, I really like this
package and want it working :)

Your help is also much appreciated for me.


El dc., 11 març, 2015 a les 16:27, Jonathan Reinink (<
notifications@github.com>) va escriure:

**Comment by Lloople** [comment]
@reinink I tried the code you show to me and it returns true, the Flysystem, so Windows files aren't the problem I think.

This is the whole error page, I hope it can help you to help me.

Tell me if you need more information or more tests to do or wathever.

![image](https://cloud.githubusercontent.com/assets/5665466/6606744/09a03312-c83a-11e4-829e-44db9fb27627.png)

**Comment by Lloople** [comment]
I tried with the default configuration provided in this video and it works as expected:

https://vimeo.com/118089742

So I guess the problem is mine, with the configuration to find files in a different folder. But don't idea how to configure that...

**Comment by sebklaus** [comment]
@Lloople Just looking at your screenshot, Windows uses `\` and it's swapping to `/` half way through the path of the image. Try adjusting your reference to the image to use `\` all the way.

**Comment by reinink** [comment]
Okay, just having another look at this.

You say the source image is at `C:\Users\David\www\canae\public/uploads/pages/red.jpg`. I wonder if your server is configured correctly. The `source_path_prefix` is ADDED to whatever your base Filesystem path is, which is defined in `config/filesystems.php`. So that's most likely the problem.

By default Laravel sets your local filesystem path to the storage folder via `storage_path('app')`. So, if you work out what you've done here, you'll end up with a final path something like:

```php
C:\Users\David\www\canae\storage\app\C:\Users\David\www\canae\storage\uploads
```

That's clearly wrong.

You have a couple options. One, you could update your `cache\filesystem.php` config to use your public directory instead. However, I don't recommend that. You're better off using the storage folder. Which means you need to put your source images in the `/storage/app/uploads` folder. Then you have to update your server configuration like this:

```php
$this->app->singleton('League\Glide\Server', function ($app) {
    $filesystem = $app->make('Illuminate\Contracts\Filesystem\Filesystem');

    return \League\Glide\ServerFactory::create([
        'source' => $filesystem->getDriver(),
        'cache' => $filesystem->getDriver(),
        'source_path_prefix' => '/uploads',
        'cache_path_prefix' => '/uploads/.cache'
    ]);
});
```

That should solve your issues! Let me know if you have further trouble.

**Comment by chiragsheta** [comment]
Problem is in Library, *.jpg extension not supported
