### ISSUE TITLE
Add ability to specify Server class in ServerFactory

### ISSUE THREAD

**Issue by tyz910** [thephpleague/glide#49]
Hi, i want to extend Server class in my app. But i can not create it with ServerFactory because of hardcoded classname. Can you add some option to specify Server class. Something like this:

```
public function getServer($class = "League\Glide\Server")
{
	$server = new $class(
		$this->getSource(),
		$this->getCache(),
		$this->getApi()
	);
	$server->setSourcePathPrefix($this->getSourcePathPrefix());
	$server->setCachePathPrefix($this->getCachePathPrefix());
	$server->setBaseUrl($this->getBaseUrl());
	return $server;
}
```

**Comment by reinink** [comment]
Hmm, would it not just be easier to create your own factory class? Generally factories do have things hardcoded in, since their helpers intended to help build up your classes.

You wouldn't have to include all the options available in the default factory either. See the [setup manually](http://glide.thephpleague.com/config/the-server/#setup-manually) docs for more info on that.

**Comment by tyz910** [comment]
Yes, i can. But some way of specify class name will be easier.

**Comment by reinink** [comment]
Hello, at this point I think the `ServerFactory` makes sense as it is. It's purpose is to create the `Server` class that comes with Glide. It seems really odd to make the server an option. What if your particular server class implementation works quite different, and doesn't have the methods that are called in the factory? At that point I'd have add a server interface, which just feels like way too much effort and extra code when you could simply wire this up manually.
