### ISSUE TITLE
StackPHP integration

### ISSUE THREAD

**Issue by reinink** [thephpleague/glide#5]
As suggested with @frankdejonge, it might be good to add @stackphp support to Glide, since it's primarily an HTTP based library. Also, as per @alexbilbie's suggestion, the URL signing feature could be split out as a separate middleware as well, although I'm not exactly sure how that would work.

**Comment by h4cc** [comment]
:+1: 

@reinink Yep, first argument is the decorated HttpKernel.

**Comment by alexbilbie** [comment]
I've started work on this in [stackphp branch](https://github.com/thephpleague/glide/tree/stackphp)

**Comment by reinink** [comment]
I'm thinking we may need to do a little more work on this, so I'm going to reopen. For example, we may want to be able to define which routes get picked up by the ImageServer. For example, all requests that fall within the `/img/*` path. I think I need to install Proton and give this whole StackPHP thing a try.

**Comment by h4cc** [comment]
@reinink Selecting which routes will be passed to glide can be the task of another stack middleware. Think of it as the routing is another layer around glide provided by another middleware.

From a technical point of view, aint the `src/Middlewares/ImageServer.php` a middleware, because it is not decorating a application. Glide itself is a application that can be decorated. This is not quite obvious in the nomenclature of stackphp and the only name i know till now for such is "app".

Because of this glide's `HttpKernel` may not need to take a Kernel as first argument.

**Comment by alexbilbie** [comment]
I guess you're right in that ImageServer isn't decorating so therefore isn't really a middleware but a stackable app.

A "true" middleware in the context of Glide would be something that validates the sign key in the request object and enables the stack to continue, or throw an exception

**Comment by h4cc** [comment]
This issue also touches the question, how glide can be used.
Is there a way to use it standalone?
Integration in other systems like Silex/Symfony/Laravel/Drupal?

**Comment by reinink** [comment]
@h4cc Glide can easily be used on it's own, or within a existing app. I made a real effort to make sure it would work in really any situation. I plan to add some more examples to the documentation soon which will show how to setup Glide in a variety of common frameworks.
