### ISSUE TITLE
League\Glide\Api\Manipulator\Output::getQuality falls back to default if param is not string

### ISSUE THREAD

**Issue by honzatrtik** [thephpleague/glide#59]
```javascript
if (!ctype_digit($quality)) {
            return $default;
        }
```

returns ```$default``` value, if ```$quality``` param is integer.

**Comment by reinink** [comment]
Yes, technically the `getQuality()` method [will return](https://github.com/thephpleague/glide/blob/master/src/Api/Manipulator/Output.php#L63) the default value if a non-string is provided. However, this value will always be a string since it's accessed via the `Symfony\Component\HttpFoundation\Request` object, as you can see [here](https://github.com/thephpleague/glide/blob/master/src/Api/Manipulator/Output.php#L20).

What that means is, even if you pass in integers (like below), HttpFoundation will automatically convert them to strings, and the result is `getQuality()` should never actually recieve anything other than a `string` or `null`.

```php
$glide->outputImage(
    'kayaks.jpg',
    [
        'w' => 300,
        'q' => 50
    ]
);
```

Please let me know if you have a particular use-case where this isn't the case.

**Comment by honzatrtik** [comment]
Hello @reinink, thanks for the answer!
Im using glide like this:

```php
$request = \Symfony\Component\HttpFoundation\Request::createFromGlobals();
$variant = $request->query->getAlnum('variant', 'thumb');
$variants = [
	'thumb' => [
		'fm' => 'jpg',
		'q' => '30', // Must be string https://github.com/thephpleague/glide/issues/59
		'fit' => 'crop',
		'w' => '500',
		'h' => '375',
		'sharp' => '10',
	],
	'thumbRect' => [
		'fm' => 'jpg',
		'q' => '30', // Must be string https://github.com/thephpleague/glide/issues/59
		'fit' => 'crop',
		'w' => '300',
		'h' => '300',
		'sharp' => '10',
	],
	'detail' => [
		'fm' => 'jpg',
		'q' => '50', // Must be string https://github.com/thephpleague/glide/issues/59
		'fit' => 'crop',
		'w' => '1600',
		'h' => '1200',
	],
];

if (!isset($variants[$variant]))
{
	$response = new \Symfony\Component\HttpFoundation\Response('', 400);
	$response->send();
	die();
}

$request->query->add($variants[$variant]);
$server->outputImage($request);
```
I'm modifying request with hardcoded image variant params and passing it to outputImage method...

**Comment by reinink** [comment]
Right, that makes sense. The Glide `RequestFactory` automatically converts all parameters to strings, which prevents this issue. However, it makes sense to allow integers as well, so thanks for pointing that out!

**Comment by reinink** [comment]
Closing this ticket. I've fixed this bug and it has been merged into the master branch and will be tagged shortly when I release `v1.0`! Hopefully not long now.
