### ISSUE TITLE
HTTP status code 200 (cache) vs status code 304?

### ISSUE THREAD

**Issue by kazoostudios** [thephpleague/glide#61]
Can Glide serve images that are more aggressively browser cached - status 200 (cache) instead of 304?

**Comment by kazoostudios** [comment]
http://stackoverflow.com/questions/1665082/http-status-code-200-cache-vs-status-code-304

**Comment by reinink** [comment]
Originally Glide returned a `200` status code. Now it returns `200` for the first request, and `304` for subsequent requests. This was actually at request. See #20. I did a bunch of research into it at the time, and it seemed that returning a `304` was the correct way to do this.

I'm probably going to setup an option to define this however you want. However, in the meantime you're welcome to modify the response object manually. As per the [docs](http://glide.thephpleague.com/config/basic-usage/), you can get the response object instead of simply outputting the image right away. Something like this:

```php
$response = $server->getImageResponse();
// modify...
$response->send();
```

**Comment by reinink** [comment]
An update on this:

The next iteration of Glide will have a `ResponseFactory` interface, which will allow you to override the default response that is created to whatever you prefer. More details on that [here](https://github.com/thephpleague/glide/issues/55#issuecomment-112080513).

I'm going to close this issue since we have it covered in that other issue. However, you can expect this feature in an upcoming release.
