### ISSUE TITLE
Cache not created + No resize

### ISSUE THREAD

**Issue by xtrasmal** [thephpleague/glide#62]
Hi there,

What should I try when the cache images are not created, but images are being shown.
The images do not respond to any glide url parameters. 
This is my setup:

```php

use League\Glide\Server as GlideServer;
use Illuminate\Http\Request;

get('images/{path}', function(GlideServer $server, Request $request) {

   return $server->outputImage($request);

})->where('path', '.+');

```

The files are in ``` public_path() . 'images/files' ```

**Comment by reinink** [comment]
Hello, can you show me your `GlideServer` setup?

**Comment by kevin-thackorie** [comment]
I believe this issue is the same as [this one](https://github.com/thephpleague/glide/issues/54), which will be solved by [this pull request](https://github.com/thephpleague/glide/pull/56) that is nearing finalization.

**Comment by reinink** [comment]
Right, I've actually removed the ability to disable the cache for now, until I've had to work this out properly. If you update to version `0.3.5` this issue should go away. For now, if you don't include a `cache` parameter, it will just use the system's temporary directory as the cache.

**Comment by xtrasmal** [comment]
@reinink My setup is like you set it up in the Laravel / Glide vimeo video. 
I've been using Glide for a while now, so I might think that it is indeed the 0.3.5 I need to update to. I'll try that out and will come back here to report back.

**Comment by xtrasmal** [comment]
Right now I'm using glide ```0.3.5```

The url I'm calling: 

     http://local.site.dev.nl/images/files/digitalhallway.jpeg?w=100&h=100&fit=crop 

My route:

```php
<?php
use League\Glide\Server as GlideServer;
use Illuminate\Http\Request;

get('images/{path}', function(GlideServer $server, Request $request) {
    
    // Super simple output.
   return $server->outputImage($request);

})->where('path', '.+');
```

My service provider setup:
```php
<?php namespace Xtrasmal\MediaManager\Providers;

use Illuminate\Support\ServiceProvider;
use League\Glide\ServerFactory;

class MediaManagerServiceProvider extends ServiceProvider {

	/**
	 * Bootstrap the application services.
	 *
	 * @return void
	 */
	public function boot()
	{
		// Views
		$this->loadViewsFrom(__DIR__.'/../resources/views', 'mediamanager');

		// Publish views
		$this->publishes([
        	__DIR__.'/../resources/views' => base_path('resources/views/mediamanager')
    	], 'views');

		// Publish config
		$this->publishes([
        	__DIR__.'/../config/mediamanager.php' => config_path('mediamanager.php')
    	], 'config');
    	       
		// Publish migrations
		$this->publishes([
		    __DIR__.'/../database/migrations/' => database_path('/migrations')
		], 'migrations');

    	// Publish Assets
		$this->publishes([
		    __DIR__.'/../resources/assets' => base_path('resources/assets/mediamanager'),
		], 'resources');

		// Load Translations
	    $this->loadTranslationsFrom(__DIR__.'/../resources/assets/lang', 'mediamanager');

	    // Load routes
	    include __DIR__.'/../Http/routes.php';

	}

	/**
	 * Register the application services.
	 *
	 * @return void
	 */
	public function register()
	{

		$this->app->singleton('League\Glide\Server', function($app){
			$filesystem = $app->make('Illuminate\Contracts\Filesystem\Filesystem');
			return ServerFactory::create([
				'source' => $filesystem->getDriver(),
				'cache' => $filesystem->getDriver(),
				'source_path_prefix' => 'images',
				'cache_path_prefix' => 'images/.cache',
				'base_url' => 'images'
			]);
		});
	}

}

```

And my filesystem:

```php

	/*
	|--------------------------------------------------------------------------
	| Filesystem Disks
	|--------------------------------------------------------------------------
	|
	| Here you may configure as many filesystem "disks" as you wish, and you
	| may even configure multiple disks of the same driver. Defaults have
	| been setup for each driver as an example of the required options.
	|
	*/

	'disks' => [

		'local' => [
			'driver' => 'local',
			'root'   => public_path().'/images/files',
		],
```


The image shows up. Resizing didn't happen. Cache is not created.

**Comment by reinink** [comment]
Okay, the first issue I see is in your filesystem config. You set this the path to `public/images/files`. However, in your Glide config, you're setting the source path prefix as `images` and `images/.cache`. That would mean Glide would actually be looking for the source images in `public/images/files/images`, and would be caching images to `public/images/files/images/.cache`.

The bigger issue is that your saving your original images in the public directory. When you call `http://local.site.dev.nl/images/files/digitalhallway.jpeg?w=100&h=100&fit=crop`, your web server is actually finding the file `images/files/digitalhallway.jpeg`, which means it never hits PHP (or Glide) at all. Adding in those `GET` variables would do nothing at that point.

That's generally how URL rewriting works. If the asset is found, the web server will show it, otherwise it will fall back to `index.php` and get routed through your framework.

Normally I place my user-generated content in the default storage directory that Laravel provides, which is one directory above `public`. That way it's impossible to access those source files from a public URL, and these image requests will always be sent through the PHP framework.

If you really want to keep your source images in your public directory, you could always use `img` instead of `images` for your image URLs, which will force them through Laravel.

Update your router to:

```php
get('img/{path}', function(GlideServer $server, Request $request) {

   return $server->outputImage($request);

})->where('path', '.+');
```

Update your provider to:

```php
    public function register()
    {

        $this->app->singleton('League\Glide\Server', function($app){
            $filesystem = $app->make('Illuminate\Contracts\Filesystem\Filesystem');
            return ServerFactory::create([
                'source' => $filesystem->getDriver(),
                'cache' => $filesystem->getDriver(),
                'cache_path_prefix' => '.cache',
                'base_url' => 'img'
            ]);
        });
    }
```

Then you would access your images at: `http://local.site.dev.nl/img/files/digitalhallway.jpeg?w=100&h=100&fit=crop`. Hope that helps!

**Comment by xtrasmal** [comment]
@reinink thanks
