### ISSUE TITLE
Combine crop and resize

### ISSUE THREAD

**Issue by Yoyogi** [thephpleague/glide#66]
Hello,

Is it possible to resize an image before cropping it ?
For instance, I have a large image 2000x2000px. I want to get only the part of 100x200px located at coordinates (500px;500px), but in a smaller size like 50x100px. Is it possible to do something like this ?

Thanks

**Comment by reinink** [comment]
Nope, and this is intentional. It's almost always better to crop before resizing, and this is actually modelled after the [Imgix](http://www.imgix.com/) API. You can still accomplish the same thing, you simply need to perform your crop operation at the larger size, which might require some basic calculations.

Often cropping libraries provide the ability to specifiy the cropping dimensions based on the original image as well. For example, jCrop allows you to do this using the [Explicit Sizing Method](http://deepliquid.com/content/Jcrop_Sizing_Issues.html#Explicit_Sizing_Method).
