### ISSUE TITLE
Should the output manipulator actually be a manipulator?

### ISSUE THREAD

**Issue by studiowbe** [thephpleague/glide#76]
This gave me a bit of trouble when trying to add a custom manipulator:

All manipulators return an instance of Intervention\Image\Image which gets passed on to the next manipulator. When the Output manipulator is executed, it sets the `$encoded` parameter for the Image, so any further manipulations will not be visible in the result.

For this reason it should always be the last element in the array passed to Api::setManipulators():

This works as expected:
```
$server->getApi()->setManipulators([
    new \League\Glide\Api\Manipulator\Size(),
    new \League\Glide\Api\Manipulator\Output(),    
]);
```

This doesn't (anything to do with the Size manipulator is ignored):
```
$server->getApi()->setManipulators([
    new \League\Glide\Api\Manipulator\Output(),    
    new \League\Glide\Api\Manipulator\Size(),    
]);
```

In my opinion "outputting" and "manipulating" are two different concepts: first you manipulate the image and after that you encode it in a given format with a certain quality etc. Therefore I think it would make sense to remove the Output Manipulator and replace it with an API\Output class that handles the encoding. This class would be called at the end of Api::run(), right before `return $image->getEncoded()`

**Comment by reinink** [comment]
You are 100% correct, the output manipulator must come last. I can appreciate that it feels like a separate task. However, I do still see it as a manipulator, in that it manipulates the format and the quality. Truthfully, it should probably be called the `Encode` manipulator. In fact I'm going to change it to that in the next release (which has a bunch of breaking changes anyway).

Further, this manipulator must tie into the Api loop somehow, as it uses the manipulation values (`fm` and `q`), and the current instance of the `Image`. And, the encoded must occur before the `getEncoded()` is called in the `Api` class. So moving it elsewhere gets really complicated. My goal was to have all interaction with the `Image` class remain within the `Api` and `Manipulators` classes.

I think the best solution here:

- Rename the `Output` manipulator to `Encode`, since this is more accurate and better reflects the task of this manipulator
- Add a note to the documentation that an encoding manipulator must come last (be it the one that is supplied with Glide, or a custom one)

**Comment by jaimz22** [comment]
I just wanted to make a comment on this issue. 

Personally I don't see the change to documentation and the class name as being a fix.

I don't plan on changing the format, or quality of an image, therefore, I shouldn't need to use the Encoder manipulator; because I don't intend on manipulating the images in either way. Changing the quality and/or format are in fact manipulations.

HOWEVER! if you don't use the encoder manipulator you don't get output at all. 

Please, consider the following:

```php
    // we only plan on changing the size of images
    // so we're only going to use this manipulator (no need for code we don't use!)
    $manipulators = [
	        new \League\Glide\Manipulators\Size(2000*2000)
    ];
    
    $source = 'somePath/';
    $cache = 'someOtherPath/whatever';
    $api = new Api($imageManager, $manipulators);
    $server = new Server($source,$cache,$api);

    $server->setResponseFactory(new SymfonyResponseFactory());
    $response = $server->getImageResponse('dankMeme.jpg',['w'=>320,'h'=>240]);

    return $response;
```

This writes a 0 byte cache file, with a mime type of inode/x-empty, and the response is completely empty as a result.

This means that the Encoder manipulator is actually a requirement and therefore shouldn't even be allowed to be configured (read excluded)

I suggest that the Encoder manipulator be changed to be responsible for only the manipulation of the image's format and quality, while the actual output of the image is handled elsewhere. possibly in the end of the `League\Glide\Api\Api::run()` method before the line `return $image->getEncoded()`. 

Additionally, I'd suggest adding a call to `$image->isEncoded()` to make sure the encoded image is even set before attempting to return the data.
