### ISSUE TITLE
Large Installation Cache Lifespan and Purging Cache

### ISSUE THREAD

**Issue by nedens** [thephpleague/glide#77]
Just installed into a large system on Amazon EC2 with a backbone storing images on S3. Could not find anywhere in the docs how often the system checks the source to see if it has change and regenerates the cached copy or if there is a way to force purge an item from the cache and create a new resized image (in the event that the source has changed). 

Any help greatly appreciated as I wasn't sure where I could send this request/question

**Comment by reinink** [comment]
Right now there is no way to purge the cache for an existing source file. However, this is coming soon in an upcoming release of Glide. See [here](https://github.com/thephpleague/glide/issues/7#issuecomment-112161637) for more details.

Also, Glide doesn't check to see if the source image has changed, and I'm not sure it ever will. Glide caches the manipulated images aggressively, so checking for source changes on every request isn't really feasible. Having said that, when I've had to get around this problem in the past, I'm simply appended a `&version=1` to the query string. This works great because it breaks both the browser caching, and will also cause Glide to regenerate the image since the cache filename will be different. The cache filenames are simply a MD5 hash of the path and query strings, which you can see [here](https://github.com/thephpleague/glide/blob/master/src/Server.php#L186).

Again, watch for the next major release of Glide, which will allow the deleting of manipulated images in the cache based on the source image filename. However, it's good to remember that even when doing that, a user would still have to refresh their browser to force a browser cache refresh.

I hope that helps!
