### ISSUE TITLE
404 When Accessing Image

### ISSUE THREAD

**Issue by zslabs** [thephpleague/glide#90]
Was running into the exact same issue as http://stackoverflow.com/questions/30332539/laravel-glide-not-finding-images-at-urls-with-extension

Have had to disable caching in NGINX:

    # cache.appcache, your document html and data
    location ~* \.(?:manifest|appcache|html?|xml|json)$ {
      expires -1;
      access_log logs/static.log;
    }
    
    # Feed
    location ~* \.(?:rss|atom)$ {
      expires 1h;
      add_header Cache-Control "public";
    }
    
    # Media: images, icons, video, audio, HTC
    location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc)$ {
      expires 1M;
      access_log off;
      add_header Cache-Control "public";
    }
    
    # CSS and Javascript
    location ~* \.(?:css|js)$ {
      expires 1y;
      access_log off;
      add_header Cache-Control "public";
    }
    
    # WebFonts
    # If you are NOT using cross-domain-fonts.conf, uncomment the following directive
    location ~* \.(?:ttf|ttc|otf|eot|woff|woff2)$ {
     expires 1M;
     access_log off;
     add_header Cache-Control "public";
    }

This occurred when switching from local to S3, and after disabling these rules I can access the images again. Any tips?

**Comment by reinink** [comment]
Did you figure out what was wrong?

**Comment by zslabs** [comment]
Hey @reinink,
I decided to be more explicit with that NGINX directive, which I'm not 100% happy about, but it's broken without. Meaning the .cache folder is ignored. What's odd is locally it worked fine, but as soon as I changed fileDrivers with the same server config, everything stopped working and even reverting the fileDriver did not resolve the issue. Basically pushed me into S3 for everything as well, which spawned https://github.com/thephpleague/glide/issues/93

**Comment by reinink** [comment]
Hmm, am I correct in understanding that your .cache folder is in your public folder somewhere?

**Comment by zslabs** [comment]
They are currently in the `storage` directory, so not public. I have a route that maps to a controller that returns the image from the storage directory to protect the generation of random image sizes.

**Comment by reinink** [comment]
Hmm, so I understanding correctly, you are manually outputting images, and not return a response object? Glide uses the streams functionality provided by Flysystem, which uses the stream functionality offered in the Amazon PHP SDK. If you're not doing this correctly, it actually has to download the entire image first, and then output it, as opposed to outputting it as it downloads.

Further, if you're manually outputting images, you must properly set far-future headers as well, otherwise the images will never be cached by the browser. Combined, these two issues will cause S3 to feel very slow, especially if you're loading large images.

I'd strongly suggest using `$server->getImageResponse()`, and letting your framework handle the outputting of the image. If you're using version 0.3, only HttpFoundation is supported, meaning it will work with Symfony, Laravel, and other HttpFoundation supported frameworks. If you're using the upcoming version 1.0, this can be done with other frameworks as well. See [here](http://glide.thephpleague.com/1.0/config/responses/) for more information.

**Comment by reinink** [comment]
Also, if you're concerned about the generation of random image sizes, then you'll definitely want to look at securing your images with HTTP signatures. This solve this exact problem. More details [here](http://glide.thephpleague.com/1.0/config/secure-images/).

**Comment by reinink** [comment]
Closing since I haven't heard anything. Please feel free to response either way if need further help.

**Comment by juukie** [comment]
FYI, I have a nginx expires config (based on h5bp) which is used for multiple websites. Some use Glide and url's start with `/img/` or `/photos/`. So as long as I stick with this convention, I'm fine.

I'm having this in my expires.conf:
```
location ~ ^/(img|photos)/ {
  location ~* \.(?:jpg|jpeg|gif|png)$ {
    expires 1y;
    access_log off;
    add_header Cache-Control "public";

    # Pass request to Laravel if a static file does not exist.
    # It even checks for a directory but that isn't needed 🤔
    try_files $uri $uri/ /index.php?$query_string;
  }
}

# Media: images, icons, video, audio, HTC
location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc)$ {
  expires 1y;
  access_log off;
  add_header Cache-Control "public";
}
```
