### ISSUE TITLE
Adding custom filters

### ISSUE THREAD

**Issue by coding-sunshine** [thephpleague/glide#97]
Hi,
How can I add my own custom filters to Filt section ?

Thanks

**Comment by reinink** [comment]
Hello! Thanks for your interest in Glide! This is a great question, and something I hope to write documentation about in the near future. What you need to do is two things:

First, you need to create a new custom manipulator as per your needs. Keep in mind that you will use the [Intervention](https://github.com/Intervention/image) image library when doing your manipulations. You can find lots of example [here](https://github.com/thephpleague/glide/tree/master/src/Manipulators).

Second, you'll need to manually wire-up your Glide instance, since the Glide factory only uses the image manipulators that come with Glide. You can find an example of that [here](http://glide.thephpleague.com/1.0/config/the-server/#setup-manually).

Just remember that the existing `League\Glide\Manipulators\Encode` manipulator must come last.

Good luck!
