### ISSUE TITLE
How can i use latest 1.0 version

### ISSUE THREAD

**Issue by coding-sunshine** [thephpleague/glide#98]
I am working on a project for which I need few functionalities of version 1.0, How can i install it?

**Comment by joshrhykerd** [comment]
Hello @coding-sunshine I had the same question a little while back and it was answered here: https://github.com/thephpleague/glide/issues/7#issuecomment-123707440

Also I've been using 1.0 ever since I posed the question and have not had any issues. Let me know if you come upon any questions with the upgrade. Glad to help, but it's pretty straight forward.

Josh

**Comment by reinink** [comment]
Sorry folks, version 1 is basically ready to go, just trying to finalize a few things before I tag this. Soon! :+1:

**Comment by coding-sunshine** [comment]
thanks for the help @joshrhykerd that worked fine.
And @reinink I love your work anyways and we understand that delays happen at times. Till now I am happy with dev-master. It doesn't break anything for me yet :)

**Comment by Markohs** [comment]
I'm switchin to dev-master too since that 1.0 release looks like is months away in the future. Thanks for your work, @reinink. :)

**Comment by reinink** [comment]
Hey all, Glide 1.x is coming before 2016! :tada:

Until then, remember to never use `dev-master`, but always a tagged version of Glide. For example:

```
"league/glide": "dev-master#4f7e56b260573750c3cff7b8623ad2965700de61",
```

**Comment by reinink** [comment]
Glide 1.0.0 was just tagged! See the [changelog](http://glide.thephpleague.com/1.0/changelog/) for a complete list of changes.
